apiVersion: apps/v1
kind: Deployment
metadata:
  name: mul-service
spec:
  replicas: {{ .Values.mul.replicaCount }}
  selector:
    matchLabels:
      app: mul-service
  template:
    metadata:
      labels:
        app: mul-service
    spec:
      containers:
        - name: mul-service
          image: "{{ .Values.image.repository }}/mul-service:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3003
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 20
